spring:

      datasource:

                url: 
                username: 
                password: 

      jpa:

          show-sql:
          hibernate:
                    ddl-auto:

          properties: 
                    hibernate:
                              dialect:  